function Tclad = cladProfile( r, T_infinity, q, Rv, Rfoc, Rg, R, kc, hc)
    
    Tclad = - ( q .* Rg ./ ( 3 .* kc ) ) .* ( Rv.^3 ./ Rfoc  - Rfoc.^2 ) ./ r + ...
            T_infinity + ...
            ( q .* Rg ./ 3 ) .* ( Rv.^3 ./ Rfoc - Rfoc.^2 ) .* ...
            ( 1 ./ ( kc .* R) -  1 ./ ( hc .* R.^2 ) );
end 

